name: isaacandpat
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.57363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7d1da'
    - '#040404'
    - '#2d2d2f'
    - '#656567'
    - '#8a8987'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
